spring:
  application:
    name: SAADemoApp

  data:
    redis:
      host: localhost
      port: 6379
      database: 1

  ai:
    dashscope:
      api-key: ${qwenKey}
    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}
        index-name: saademo

apikey:
  qwenKey: ${qwenKey}

server:
    port: 8888