spring:
  application:
    name: SAADemoApp

  data:
    redis:
      host: localhost
      port: 6379
      database: 1

  ai:
    dashscope:
      api-key: ${qwenKey}

apikey:
  qwenKey: ${qwenKey}


server:
    port: 8888